services:
  recipebook-backend:
    build: .
    ports:
      - "4000:4000"
    image: anoosha1221/recipebook-backend
    networks:
      - recipe-book-network
    depends_on:
      - db
    environment:
      - DB_USERNAME=postgres
      - DB_PASSWORD=Anu@123
      - DB_HOST=recipe-backend-db-1
      - DB_NAME=recipes
      - PORT=4000
      - ACCESS_TOKEN_SECRET=db76f663790163eef52a264bddd136315f1f0d905b903f9749f3172a9f684734d23c1ca14d3776690383ae12495e4658f3b967a9bdcbde72425836fa92d426ad
  db:
    healthcheck:
      test: pg_isready -h postgres -U postgres
      interval: 2s
      timeout: 5s
      retries: 15
    ports:
      - "5431:5432"
    image: postgres
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: Anu@123
      POSTGRES_DB: recipes
    networks:
      - recipe-book-network

networks:
  recipe-book-network:
    name: recipe-book-network
