name: RecipeBook Postgre Backend
run-name: RecipeBook
on:
  push:
    branches:
      - main
      - recipe-features
  pull_request:
    branches:
      - main
jobs:
  Workflow-for-Backend:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15-alpine
        env:
          POSTGRES_PASSWORD: mysecretpassword
          POSTGRES_DB: my_test_db
        ports:
          - "5432:5432"
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "21"
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm run test
